name: Sync Fork and Trigger Workflow

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜运行一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ledccn/iyuuplus-dev
        ref: master
        token: ${{ secrets.PAT }}

    - name: Set up git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/master

    - name: Push changes
      run: git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

  trigger:
    needs: sync
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Trigger dependent workflow
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/anxinJ/iyuuplus-dev/actions/workflows/build.yml/dispatches \
          -d '{"ref":"master"}'
