name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜运行一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: anxinJ/iyuuplus-dev
        ref: master
        token: ${{ secrets.PAT }}
    
    - name: Set up git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Add upstream repository
      run: git remote add upstream https://github.com/ledccn/iyuuplus-dev.git

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/master

    - name: Push changes
      run: git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
